version: '3'
services:
    mysql:
        image: mysql:5.7
        ports:
            - '33061:3306'
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD

    crt_symfony_1:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: crt_symfony_1:lastest
        ports:
            - '8080:8080'
        depends_on:
            - mysql