version: '3'
services:
    mysql:
        image: mysql:5.7
        ports:
            - '33061:3306'
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD

    crt_symfony_1:
        image: linbis/crt_symfony_1:1.0
        container_name: crt_symfony_1
        ports:
            - '8080:8080'
        depends_on:
            - mysql